<!DOCTYPE html>
<html>
<head>
	<title></title>

	<script src="https://use.fontawesome.com/452826394c.js"></script>
	<link rel="stylesheet" type="text/css" href="./css/style.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
</head>
<body>
	<header>
		<?php include ('header.php');?>
	</header>
	<main>
		<?php include $template.'.phtml';?>
	</main>
	<footer>
		<?php include ('footer.php');?>
	</footer>
<script type="text/javascript" src="./js/main.js"></script>
</body>
</html>