<div id="customer">
<h1>Enregistrement d'un produit</h1>

<form method="POST" action="produit.php" enctype="multipart/form-data">
	<fieldset>
		<table>
			<thead></thead>
			<tbody>
				<tr>
					<td>
						<input type="text" name="title" placeholder="Nom du produit">
					</td>
					<td>
						<input type="text" name="izena" placeholder="produktuaren izena">
					</td>
				</tr>
				<tr>
					<td>
						<textarea name="description_long"placeholder="Description Longue"></textarea>
					</td>
					<td>
						<textarea name="deskribapen_luzea"placeholder="Deskribapen Luzea"></textarea>
					</td>
				</tr>
				<tr>
					<td>
						<textarea name="description_short"placeholder="Description Courte"></textarea>
					</td>
					<td>
						<textarea name="deskribapen_laburra"placeholder="Deskribapen Laburra"></textarea>
					</td>
				</tr>
				<tr>
					<td>
						Catégorie :
					</td>
					<td>
						<select name="categoryId">
							<?php foreach($categories as $category): ?>
							<option value="<?= $category['Id']?>"><?= $category['Category']?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<input type="text" name="quantity" placeholder="Quantité">
					</td>
					<td>
						<select name="unityId">
							<?php foreach($unities as $unity): ?>
							<option value="<?= $unity['Id']?>"><?= $unity['Unity']?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<input type="text" name="weight" placeholder="Poids Moyen">
					</td>
				</tr>
				<tr>
					<td>
						<input type="text" name="price" placeholder="prix">
					</td>
					<td>
						eusko/euro
					</td>
				</tr>
				<tr>
					<td>
						Producteurs :
					</td>
					<td>
						<select name="producerId">
							<?php foreach($producers as $producer): ?>
							<option value="<?= $producer['Producer_Id']?>"><?= $producer['Producer_Name']?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						Label Idoki :
					</td>
					<td>
						<select name="Idoki">
							<option value="non">non</option>
							<option value="oui">oui</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						Label AOP :
					</td>
					<td>
						<select name="AOP">
							<option value="non">non</option>
							<option value="oui">oui</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						Label AB :
					</td>
					<td>
						<select name="AB">
							<option value="non">non</option>
							<option value="oui">oui</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						Label En Conversion :
					</td>
					<td>
						<select name="Conversion">
							<option value="non">non</option>
							<option value="oui">oui</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>
						Produit du mois :
					</td>
					<td>
						<select name="Promotion">
							<option value="non">non</option>
							<option value="oui">oui</option>
						</select>
					</td>
				</tr>
			</tbody>
		</table>
		<ul>
		<p>Enregistrement d'une photo :</p>
		<input type="hidden" name="MAX_FILE_SIZE" value="4194304">
		<li><input type="file" name="photo" accept=".jpg, .jpeg, .png"></li>
		<li>
			<input type="text" name="ImageDescription" placeholder="Description de la photo">
			<input type="text" name="IrudiDeskribapen" placeholder="Irudiaren deskribapena"></li>
		</ul>

		<button type="submit">Créer le produit</button>


	</fieldset>

</form>

<h1>Liste des Produits</h1>

<table id="list">
	<thead>
		<tr>
			<th>Nom</th>
			<th>Izenburua</th>
			<th>Description Longue</th>
			<th>Deskribapen Luzea</th>
			<th>Catégorie</th>
			<th>Quantité</th>
			<th>Prix</th>
			<th>Poids Moyen</th>
			<th>Producteur</th>
			<th>Idoki</th>
			<th>AOP</th>
			<th>Bio</th>
			<th>Conversion</th>
			<th>Promotion</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<form id="search" method="POST" action="produit.php">
			<td><input type="text" name="recherche" id="recherche" placeholder="recherche"></td>
			<td><input type="text" name="bilaketa" id="bilaketa" placeholder="bilaketa"></td>
			<td><button name="search">Filtrer</button></td>
			</form>
		</tr>
		<?php foreach($products as $product): ?>
			<tr class="modify" id="<?= $product['Product_Id']?>">
				<td><?= $product['Title']?></td>
				<td><?= $product['Izenburua']?></td>
				<?php $cut = wordwrap($product['Description_Long'], 50, "[...]$	", false); ?>
				<?php $array = explode("$", $cut); ?>
				<?php $extract = $array[0]; ?>
				<td><?= nl2br(htmlspecialchars($extract))?></td>
				<?php $cut = wordwrap($product['Deskribapen_Luzea'], 50, "[...]$	", false); ?>
				<?php $array = explode("$", $cut); ?>
				<?php $extract = $array[0]; ?>
				<td><?= nl2br(htmlspecialchars($extract))?></td>
				<td><?= $product['Category']?></td>
				<td>
					<form method="POST" action="modify.php?type=product&id=<?= $product['Product_Id']?>">
					<input type="hidden" name="id_Product" value="<?= $product['Product_Id']?>">
					<input type="text" name="Quantity_Product" value="<?= $product['Quantity']?>" min='0'>
					<button type="submit" name="modifyQuantity">Modifier</button>
					</form>
				</td>
				<td>
					<form method="POST" action="modify.php?type=product&id=<?= $product['Product_Id']?>">
					<input type="hidden" name="id_Product" value="<?= $product['Product_Id']?>">
					<input type="text" name="Price_Product" value="<?= $product['Price']?>" min='0'>
					<button type="submit" name="modifyPrice">Modifier</button>
					</form>
				<td><?= $product['Weight']?></td>
				<td><?= $product['Producer_Name']?></td>
				<td><?= $product['Product_Label_Idoki']?></td>
				<td><?= $product['Product_Label_AOP']?></td>
				<td><?= $product['Product_Label_Bio']?></td>
				<td><?= $product['Product_Label_Conversion']?></td>
				<td><?= $product['Product_Promotion']?></td>
				<td>
					<form class="list" method="POST" action="modify.php?type=product&id=<?= $product['Product_Id']?>">
					<input type="hidden" name="id_Product" value="<?= $product['Product_Id']?>">
					<!-- <button type="submit" name="modify">Modifier</button> -->
					<button type="submit" name="delete">Supprimer</button>
					</form>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

</div>