<div id="conditions">

<?php if ($langue == 'fr'): ?>
	<h1>Conditions générales de ventes</h1>

			<p>Les présentes conditions générales de vente régissent l'ensemble des relations entre L'Epicerie Fermière d'Euskal Herri dont le siège social Bide Artea, RN10, 64122 Urrugne, immatriculée au RCS de Bayonne sous le N° 797 391 463 et ses clients.</p>
			<p>Le contenu (hors design) du site est la propriété de L'Epicerie Fermière d'Euskal Herri en sa totalité, ainsi que l'ensemble des droits y afférents.</p>
			<p>Toute reproduction, intégrale ou partielle est strictement interdite.</p>

		<h2>1. Acceptation des conditions</h2>

			<p>Préalablement à toute transaction, le client reconnaît avoir pris connaissance des présentes conditions générales de vente et déclare expressément les accepter sans réserve dès lors qu'il passe commande sur le présent site.</p>

		<h2>2. Fiches produits</h2>

			<p>L'Epicerie Fermière d'Euskal Herri  fait connaître au client l'ensemble des caractéristiques essentielles des articles offerts et livrables.</p>
			<p>Ces caractéristiques concernent les poids, les quantités, le conditionnement et apparaissent dans les écrans de présentation des produits proposés à la vente.</p>
			<p>Les photographies illustrant les produits sont fournies à titre indicatif.</p>
			<p>Les photographies de présentation des produits proposés dans le catalogue électronique ne sont pas contractuelles et ne peuvent engager la responsabilité du vendeur à l'égard de l'acheteur.</p>

		<h2>3. La commande</h2>

			<p>Le client passe commande en cliquant sur l'icône "validez la commande".</p>
			<p>Les systèmes d'enregistrement automatiques de L'Epicerie Fermière d'Euskal Herri sont considérés comme valant preuve, de la nature, du contenu et de la date de la commande.</p>
			<p>Toute commande passée sur le site implique l'acceptation des présentes conditions générales de vente.</p>

		<h2>4. Confirmation de la Commande</h2>

			<p>Ce n'est qu'à compter de la confirmation de la commande par L'Epicerie Fermière d'Euskal Herri que la vente est conclue.</p>
			<p>Dans le cas où un ou plusieurs articles ne seraient pas disponibles dans les conditions prévues par le service, L'Epicerie Fermière d'Euskal Herri prendra contact avec le client par courrier électronique ou par téléphone pour suivre ses instructions avant toute validation de commande.</p>
			<p>L'Epicerie Fermière d'Euskal Herri se réserve le droit de refuser toute commande d'un client avec lequel existerait un litige.</p>

		<h2>5. Livraisons</h2>

			<p>Le client a connaissance que les articles commandés sur le site lui seront livrés par le service de livraison L'Epicerie Fermière d'Euskal Herri.</p>
			<p>Les commandes sont livrées par le service de livraison L'Epicerie Fermière d'Euskal Herri:</p>
			<p class="list"> à domicile à partir de 20€ TTC d'achats</p>
			<p class="list"> en point-relais, points collectifs, lieux de travail à partir de 16€ d'achats </p>
			<p>Les livraisons sont assurées dans le créneau horaire proposé par L'Epicerie Fermière d'Euskal Herri  et sélectionné par le client lors de sa commande.</p>
			<p>Si L'Epicerie Fermière d'Euskal Herri se trouve dans l'impossibilité de respecter les horaires prévus, le client en est informé le jour même, par tous moyens tels que courrier électroniques, téléphone, etc.</p>
			<p>Les retards éventuels ne donnent pas droit au client de réclamer des dommages et intérêts.</p>
			<p>Lorsque la remise de la marchandise au client n'est pas possible du fait de ce dernier, L'Epicerie Fermière d'Euskal Herri se réserve le droit de lui facturer une participation forfaitaire aux frais de préparation de 10 € TTC.</p>
			<p>Le lieu de livraison est choisi par le client lors de sa commande.</p>
			<p>En cas d'erreur dans le libellé des coordonnées du destinataire, Gustoki ne saurait être tenu responsable de l'impossibilité dans laquelle il pourrait être de livrer sa commande.</p>

		<h2>6. Cas de force majeure</h2>

			<p>Tous les événements, de quelque nature qu'ils soient, échappant à la volonté du producteur et/ou de L'Epicerie Fermière d'Euskal Herri, irrésistibles, imprévisibles et tendant à retarder ou à empêcher l'exécution de la commande constituent de convention expresse une cause de suspension et/ou d'extinction des obligations du producteur et/ou de L'Epicerie Fermière d'Euskal Herri envers l'acheteur sans indemnité au profit de l'acheteur.</p>

		<h2>7. Le prix</h2>

			<p>Les tarifs indiqués sont exprimés en euro, toutes taxes comprises.</p>
			<p>La facturation est effectuée en tenant compte du tarif affiché au moment de la commande.</p>
			<p>Le vendeur se réserve le droit de modifier à tout moment les prix de vente figurant sur le catalogue électronique.</p>

		<h2>8. Paiement</h2>

			<p>Par chèque bancaire, espèces et euskos.</p>
			<p>Le client doit acquitter le règlement intégral de sa commande à la livraison de celle-ci selon les modalités indiquées sur le site.</p>

		<h2>9. Responsabilité</h2>

			<p>Toutes les réclamations doivent être adressées à L'Epicerie Fermière d'Euskal Herri par courrier électronique.</p>
			<p>La qualité du contenu des paniers et colis dépend des conditions de production et L'Epicerie Fermière d'Euskal Herri décline toute responsabilité vis à vis d'allergies ou de mauvaises conservations des aliments.</p>
			<p>L'Epicerie Fermière d'Euskal Herri ne saurait être tenu responsable de tout problème sanitaire lié à une mauvaise préparation des produits qu'il commercialise. En effet, les produits livrés sont entre autres des fruits et légumes crus, qui ne peuvent être consommés en l'état. Ils doivent être lavés et préparés (découpe, cuisson, etc.) par le client avant consommation.</p>

		<h2>10. Droit de rétractation</h2>

			<p>Conformément à l'article L.121-16 et suivants du code de la consommation, l'acheteur dispose d'un délai de rétractation de 7 jours francs à compter de la réception de la commande pour retourner tous produits à L'Epicerie Fermière d'Euskal Herri pour échange ou remboursement sans pénalités à L'Epicerie Fermière d'Euskal Herri. Ce droit ne peut s'appliquer aux denrées périssables.</p>

		<h2>11. Droit d'accès au fichiers</h2>

			<p>Pour le bon déroulement de la commande, les données nominatives recueillies font l'objet d'un traitement informatique.</p>
			<p>Conformément à la loi du 06 Janvier 1978 relative à l'informatique, aux fichiers et aux libertés le client dispose à tout moment d'un droit d'accès, de modification et de rectification de ces données.</p>
			<p>Pour exercer l'un de ces droits, le client doit se connecter à son compte en utilisant son adresse electronique et son mot de passe, défini par lui-même.</p>

		<h2>12. Litiges</h2>

			<p>En cas de litige, le client s'adressera en priorité à L'Epicerie Fermière d'Euskal Herri pour rechercher une solution amiable. </p>


<?php else: ?>
	<h1>Salmenta baldintza orokorrak</h1>



<?php endif; ?>

</div>