<div id="delivery">
	<?php if ($langue == 'fr'): ?>
		<h1>La livraison chez Gustoki</h1>
		<section>
			<h2>Gustoki, toujours au plus près de vous</h2>
			<p>Nous allons chercher les meilleurs produits du Pays Basque et nous vous les apportons au plus près de chez vous ou de vos activités.</p>

<table id="exemple">
	<thead></thead>
	<tbody>
		<tr>
			<td class="retrait">Retrait</td>
		</tr>
		<tr>
			<td class="livraison">Livraison</td>
		</tr>
	</tbody>
</table>

<table id="planning">
	<thead>
		<tr>
			<th>horaires</th>
			<th>MARDI</th>
			<th>MERCREDI</th>
			<th>JEUDI</th>
			<th>VENDREDI</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td rowspan="2">7h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">8h</td>
			<td></td>
			<td rowspan="4" class="livraison">St Jean de Luz: Jalday, Polyclinique</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">9h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>

		</tr>
		<tr>
			<td rowspan="2">10h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">11h</td>
			<td></td>
			<td rowspan="5" class="retrait">Drive Gustoki</td>
			<td></td>
			<td rowspan="3" class="retrait">Drive Gustoki</td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">12h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">13h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">14h</td>
			<td></td>
			<td rowspan="9" class="livraison">Hendaye<br>Béhobie<br>Biriatou<br>Ascain<br>St Pée<br>Biarritz<br>Bidart<br>Anglet</td>
			<td rowspan="9" class="livraison">BAB<br>Bassussary<br>Arcangues</td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">15h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">16h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td rowspan="7" class="retrait">Drive Gustoki</td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">17h</td>
			<td rowspan="4" class="retrait">Retrait Drive Gustoki</td>
			<!-- <td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<td rowspan="2">18h</td>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">19h</td>
			<td rowspan="4" class="livraison">Urrugne<br>St Jean de Luz: Marinella, Karsinenea<br>Ciboure<br>Ascain/St Pée</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">20h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>	
			<td rowspan="2">21h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		
	</tbody>
</table>
</section>

<?php else: ?>
		<h1>Gustoki banatzea</h1>
		<section>
			<h2>Gustoki, beti gertuago</h2>
			<p>Euskal Herriko produktu onenak bilatuko ditugu eta zure etxera edo zure jarduerekin ahalik eta gertuen ekarriko ditugu.</p>

<table id="exemple">
	<thead></thead>
	<tbody>
		<tr>
			<td class="retrait">Erretiratzea</td>
		</tr>
		<tr>
			<td class="livraison">Banatze</td>
		</tr>
	</tbody>
</table>


			<table id="planning">
	<thead>
		<tr>
			<th>ordutegia</th>
			<th>ASTEARTEA</th>
			<th>ASTEAZKENA</th>
			<th>OSTEGUNA</th>
			<th>OSTIRALA</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td rowspan="2">7h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">8h</td>
			<td></td>
			<td rowspan="4" class="livraison">Donibane Lohitzun: Jalday, Poliklinika</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">9h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>

		</tr>
		<tr>
			<td rowspan="2">10h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">11h</td>
			<td></td>
			<td rowspan="5" class="retrait">Drive Gustoki</td>
			<td></td>
			<td rowspan="3" class="retrait">Drive Gustoki</td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">12h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">13h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">14h</td>
			<td></td>
			<td rowspan="9" class="livraison">Hendaia<br>Pausu<br>Biriatu<br>Azkaine<br>Senpere<br>Miarritze<br>Bidarte<br>Angelu</td>
			<td rowspan="9" class="livraison">BAB<br>Basusari<br>Arrangoize</td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">15h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">16h</td>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td rowspan="7" class="retrait">Drive Gustoki</td>
		</tr>
		<tr>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">17h</td>
			<td rowspan="4" class="retrait">Drive Gustoki</td>
			<!-- <td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<td rowspan="2">18h</td>
			<!-- <td></td>
			<td></td>
			<td></td> -->
			<!-- <td></td> -->
		</tr>
		<tr>
			<!-- <td></td>
			<td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">19h</td>
			<td rowspan="4" class="livraison">Uruña<br>Donibane Lohitzun: Marinella, Karsinenea<br>Ziburu<br>Azkaine<br>Senpere</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td rowspan="2">20h</td>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<!-- <td></td> -->
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>	
			<td rowspan="2">21h</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		
	</tbody>
</table>
</section>

<?php endif; ?>

</div>