<?php if ($langue == 'fr'): ?>

	<h1>Réinitilisation du mot de passe :</h1>

	<section id="mail">
		<h2>Etape 1 sur 3</h2>
		<label for="email">Renseigner votre courriel :</label>
		<input type="email" name="email">
		<input type="hidden" name="lang" value="<?= $langue ?>">
		<button class="mail">Envoyer</button>
	</section>
	
	<section>
		<h2>Etape 2 sur 3</h2>
		<div class="container"></div>
		<button id="result" class="hide">Valider</button>

	</section>

	<section>
		<h2>Etape 3 sur 3</h2>
		<p id="endOfProcedure" class="hide">Vous allez recevoir un mail pour réinitialiser votre mot de passe.</p>
	</section>



<?php else: ?>

	<h1>Pasahitza berrezarri :</h1>

	<section id="mail">
		<h2>1/3 urratsa</h2>
		<label for="email">Idatzi zure posta elektronikoa :</label>
		<input type="email" name="email">
		<button class="mail">Bidali</button>
	</section>
	
	<section>
		<h2>2/3 urratsa</h2>
		<div class="container"></div>
		<button id="result" class="hide">Balioztatu</button>

	</section>

	<section>
		<h2>3/3 urratsa</h2>
		<p id="endOfProcedure" class="hide">Pasahitza berrezartzeko mezu elektroniko bat jasoko duzu.</p>
	</section>




<?php endif; ?>