<?php if ($langue == 'fr'): ?>
	<h1>Place du Marché</h1>

	<section id="marche">
		
		<a href="Paniers"><figure>
			<img src="img/marche/panier.jpg">
			<figcaption>Paniers</figcaption>
		</figure></a>

		<a href="Fruits-et-Légumes"><figure>
			<img src="img/marche/fruitlegume.jpg">
			<figcaption>Fruits et Légumes</figcaption>
		</figure></a>

		<a href="Viandes-et-Salaisons"><figure>
			<img src="img/marche/viande.jpg">
			<figcaption>Viandes et Salaisons</figcaption>
		</figure></a>

		<a href="Laitages"><figure>
			<img src="img/marche/frais.jpg">
			<figcaption>Laitages</figcaption>
		</figure></a>

		<a href="Epicerie-Salée"><figure>
			<img src="img/marche/epiceriesalee.jpg">
			<figcaption>Epicerie Salée</figcaption>
		</figure></a>

		<a href="Oeufs-Pains-et-Douceurs"><figure>
			<img src="img/marche/epiceriesucree">
			<figcaption>Oeufs Pains et Douceurs</figcaption>
		</figure></a>

		<a href="Conserves"><figure>
			<img src="img/marche/conserves.jpg">
			<figcaption>Conserves</figcaption>
		</figure></a>

		<a href="Liquides"><figure>
			<img src="img/marche/boisson.jpg">
			<figcaption>Liquides</figcaption>
		</figure></a>

		<a href="Bien-Etre"><figure>
			<img src="img/marche/bienetre.jpg">
			<figcaption>Bien-Etre</figcaption>
		</figure></a>

		<a href="Ailleurs"><figure>
			<img src="img/marche/ailleurs.jpg">
			<figcaption>Ailleurs</figcaption>
		</figure></a>


	</section>








<?php else: ?>
	<h1>Merkatu Plaza</h1>

	<section id="marche">
		
		<a href="Saskiak"><figure>
			<img src="img/marche/panier.jpg">
			<figcaption>Saskiak</figcaption>
		</figure></a>

		<a href="Fruituak-eta-Barazkiak"><figure>
			<img src="img/marche/fruitlegume.jpg">
			<figcaption>Fruituak eta Barazkiak</figcaption>
		</figure></a>

		<a href="Haragiak-ete-Haragi-Sendatuak"><figure>
			<img src="img/marche/viande.jpg">
			<figcaption>Haragiak eta Haragi Sendatuak</figcaption>
		</figure></a>

		<a href="Esnekiak"><figure>
			<img src="img/marche/frais.jpg">
			<figcaption>Esnekiak</figcaption>
		</figure></a>

		<a href="Salteatutako-Janariak"><figure>
			<img src="img/marche/epiceriesalee.jpg">
			<figcaption>Salteatutako Janariak</figcaption>
		</figure></a>

		<a href="Arroltze-Ogi-eta-Goxokiak"><figure>
			<img src="img/marche/epiceriesucree">
			<figcaption>Arroltze Ogi eta Goxokiak</figcaption>
		</figure></a>

		<a href="Kontserbak"><figure>
			<img src="img/marche/conserves.jpg">
			<figcaption>Kontserbak</figcaption>
		</figure></a>

		<a href="Likidoak"><figure>
			<img src="img/marche/boisson.jpg">
			<figcaption>Likidoak</figcaption>
		</figure></a>

		<a href="Ongizatea"><figure>
			<img src="img/marche/bienetre.jpg">
			<figcaption>Ongizatea</figcaption>
		</figure></a>

		<a href="Beste-Nonbait"><figure>
			<img src="img/marche/ailleurs.jpg">
			<figcaption>Beste Nonbait</figcaption>
		</figure></a>


	</section>








<?php endif; ?>