<div id="mentions">

<?php if ($langue == 'fr'): ?>
	<h1>Mentions légales</h1>

		<h2>Gustoki</h2>

			<p>Gustoki.com est le site géré et utilisé par L'Epicerie Fermière d'Euskal Herri.</p>
			<p>RCS Baiona 797 391 463</p>
			<p>SIRET 797 391 463 00016</p>
			<p>APE 4791A</p>
			<p>Le siège social de Gustoki se situe à Bide Artea, N 10 - 64122 URRUÑA (Lapurdi). Tel: <a href="tel:+33559421693">05 59 42 16 93</a>.</p>

		<h2>Responsable de publication</h2>

			<p>La responsabilité de l'ensemble du contenu de ce site est du ressord de L'Epicerie Fermière d'Euskal Herri.</p>

		<h2>Design et programmation du site</h2>
			
			<p>Ce site a été réalisé par <a href="https://www.larrun-prod.com">Larrun-Prod</a>.</p>

			<p>Les photos de divers produits ont été prise par L'Epicerie Fermière d'Euskal Herri.</p>


		<h2>Hébergement</h2>
			
			<p>en cours</p>




<?php else: ?>

	<h1>Legezko oharrak</h1>

		<h2>Gustoki</h2>

			<p>Gustoki.com "L'Epicerie Fermière d'Euskal Herri" -k kudeatu eta erabiltzen duen gunea da.</p>
			<p>RCS Baiona 797 391 463</p>
			<p>SIRET 797 391 463 00016</p>
			<p>APE 4778C</p>
			<p>"L'Epicerie Fermière d'Euskal Herri" egoitzan dago Bide Artea, N 10 - 64122 URRUÑA (Lapurdi). Tel: <a href="tel:+33559421693">05 59 42 16 93</a>.</p>

		<h2>Argitalpen arduraduna</h2>

			<p>Gune honetako eduki osoaren erantzukizuna "L'Epicerie Fermière d'Euskal Herri" -ren erantzukizuna da.</p>

		<h2>Gunearen diseinua eta programazioa</h2>
			
			<p>Gune hau <a href="https://www.larrun-prod.com">Larrun-Prod</a> -ek sortu du.</p>

			<p>Hainbat produkturen argazkiak "L'Epicerie Fermière d'Euskal Herri" -k atera zituen.</p>


		<h2>ostatua</h2>
			
			<p>abian</p>



<?php endif; ?>
	
</div>